# Gradient Descendient 

In [2]:
import numpy as np

def sigmoid(x):
    return 1/(1+np.exp(-x))

def sigmoid_prime(x):
    return sigmoid(x)*(1-sigmoid(x))

lr = 0.5
x = np.array([1,2,3,4])
y = np.array(0.5)

w = np.array([0.5,-0.5,0.3,0.1])

h = np.dot(w,x)

nn_output = sigmoid(h)

error = y-nn_output

#error term = error * nn_output * (1-nn_output)
error_term = error*(sigmoid_prime(h))



del_w =lr * error_term * x

print(nn_output)
print(error)
print(del_w)

0.6899744811276125
-0.1899744811276125
[-0.02031869 -0.04063738 -0.06095608 -0.08127477]


## Multilayer Perceptron

In [9]:
# Making a column vector
cv1 = np.array([1,2,3,4,5])
cv1[:,None]

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [10]:
cv2 = np.array([1,2,3,4,5],ndmin=2)
cv.T

array([[1],
       [2],
       [3],
       [4],
       [5]])