# PyTorch 1

In [1]:
import torch
print(torch.__version__)

1.5.0


In [2]:
def activation(x):
    #sigmoid
    return 1/(1+torch.exp(-x))

In [3]:
# Generamos datos randomicos
# Aplicamos un seed
torch.manual_seed(7)

# Los features seran 5 variables randomicas normales
features = torch.randn((1,5))
# Los pesos para nuestros dato seran variables randomicas normales tambien
weights = torch.randn_like(features) # randn_like copia el shape del argumento

#true bias term
bias = torch.randn((1,1))

In [4]:
h = torch.matmul(features,weights.T)
y_prime = activation(h+bias)

In [5]:
y_prime

tensor([[0.1595]])

In [6]:
# Notas del curso
y_prime2 = activation(torch.sum(features*weights)+bias)
y_prime2

tensor([[0.1595]])

In [7]:
# Notas del curso
# Cambiar la forma de un vector, en este caso weights:
weights2 = weights
print(weights2)

tensor([[-0.8948, -0.3556,  1.2324,  0.1382, -1.6822]])


In [8]:
# Notas del curso
weights2.reshape(-1,1)

tensor([[-0.8948],
        [-0.3556],
        [ 1.2324],
        [ 0.1382],
        [-1.6822]])

In [9]:
y = activation(torch.mm(features,weights.reshape(-1,1))+bias)

In [10]:
y

tensor([[0.1595]])

### Exercise

In [11]:
torch.manual_seed(7)

features = torch.randn((1,3))

n_input = features.shape[1]

n_hidden = 2

n_output = 1

In [12]:
print("Features: ",features)
print("Input units: ",n_input)
print("Hidden units: ",n_hidden)
print("Output units: ",n_output)

Features:  tensor([[-0.1468,  0.7861,  0.9468]])
Input units:  3
Hidden units:  2
Output units:  1


In [13]:
W1 =  torch.randn(n_input,n_hidden)
W2 = torch.randn(n_hidden,n_output)

In [14]:
print("Weights 1: ",W1)
print("Shape of Weights 1: ",W1.size())
print("-"*10)
print("Weights 2: ",W2)
print("Shape of Weights 2: ",W2.size())


Weights 1:  tensor([[-1.1143,  1.6908],
        [-0.8948, -0.3556],
        [ 1.2324,  0.1382]])
Shape of Weights 1:  torch.Size([3, 2])
----------
Weights 2:  tensor([[-1.6822],
        [ 0.3177]])
Shape of Weights 2:  torch.Size([2, 1])


In [15]:
B1 = torch.randn(1,n_hidden)
B2 = torch.randn(1,n_output)

In [16]:
print("Bias 1: ",B1)
print("Shape of Bias 1: ",B1.size())
print("-"*10)
print("Bias 2: ",B2)
print("Shape of Bias 2: ",B2.size())


Bias 1:  tensor([[0.1328, 0.1373]])
Shape of Bias 1:  torch.Size([1, 2])
----------
Bias 2:  tensor([[0.2405]])
Shape of Bias 2:  torch.Size([1, 1])


In [17]:
input_hidden = activation(torch.mm(features,W1.reshape(3,2)))

In [18]:
input_hidden.size()

torch.Size([1, 2])

In [19]:
hidden_output = torch.mm(input_hidden,W2)
hidden_output

tensor([[-0.9687]])

In [20]:
output = activation(hidden_output)

In [21]:
output

tensor([[0.2751]])

## Numpy to Torch and back

In [28]:
import numpy as np
a = np.random.rand(4,3)
a

array([[0.4117996 , 0.58731912, 0.41691766],
       [0.016623  , 0.31975151, 0.247335  ],
       [0.90542944, 0.22058855, 0.7121187 ],
       [0.59160907, 0.00447917, 0.31741182]])

In [29]:
b = torch.from_numpy(a)
b

tensor([[0.4118, 0.5873, 0.4169],
        [0.0166, 0.3198, 0.2473],
        [0.9054, 0.2206, 0.7121],
        [0.5916, 0.0045, 0.3174]], dtype=torch.float64)

In [30]:
b.numpy()

array([[0.4117996 , 0.58731912, 0.41691766],
       [0.016623  , 0.31975151, 0.247335  ],
       [0.90542944, 0.22058855, 0.7121187 ],
       [0.59160907, 0.00447917, 0.31741182]])

In [31]:
b.mul(2)

tensor([[0.8236, 1.1746, 0.8338],
        [0.0332, 0.6395, 0.4947],
        [1.8109, 0.4412, 1.4242],
        [1.1832, 0.0090, 0.6348]], dtype=torch.float64)

In [32]:
a

array([[0.4117996 , 0.58731912, 0.41691766],
       [0.016623  , 0.31975151, 0.247335  ],
       [0.90542944, 0.22058855, 0.7121187 ],
       [0.59160907, 0.00447917, 0.31741182]])

tensor([[0.9365, 0.1973, 0.0651],
        [0.0841, 0.0749, 0.1907],
        [0.8917, 0.1836, 0.0508],
        [0.5446, 0.7904, 0.6423]], dtype=torch.float64)